# Documentation: https://github.com/bschulzebaek/sw-devenv-cli/wiki

base:
  directory: "$HOME/swdev-projects/"
  remote: "git@github.com:shopware/platform.git"
devenv:
  useVhost: 1
  useSsl: 0
  urlPrefix: "dev"
  ports:
    start: 8000
    end: 10000
