#!/usr/bin/env bash

set -eu

__PROGRAM_NAME="swdev"
__PROGRAM_PATH=$(dirname $(realpath "$0"))
__VERSION=$(cd $__PROGRAM_PATH && git describe --tags --abbrev=0)
__COMMON_DIR="$__PROGRAM_PATH/common"
__CORE_DIR="$__PROGRAM_PATH/core"
__COMMAND_DIR="$__PROGRAM_PATH/commands"
__DEVENV_FILE="devenv.local.nix"

for fn in $__COMMON_DIR/*; do source $fn; done

source $__CORE_DIR/load_config

subcommand="${1:-help}"
subcommand_path="${__COMMAND_DIR}/${subcommand}"
projectName="${2:-""}"

use_working_dir

source $__CORE_DIR/input_validation
source $subcommand_path

exit 0