#!/usr/bin/env bash

PROJECT_NAME=""
BRANCH_NAME=""

while [[ $# -gt 0 ]]; do
    case $1 in
        -n|--name)
            PROJECT_NAME="$2"
            shift
            shift
            ;;
        -b|--branch)
            BRANCH_NAME="$2"
            shift
            shift
            ;;
        -*|--*)
            print_error "Unknown option $1"
            exit 1
            ;;
        *)
            shift
            ;;
    esac
done

if [ -z "$PROJECT_NAME" ]; then
    print_error "Missing required parameter --name"
    exit 1
fi

if [ -d "$PROJECT_NAME" ]; then
    print_error "Project with name '$PROJECT_NAME' already exists!"
    exit 1
fi


if [ -z "$BRANCH_NAME" ]; then
    print_info "No option for '--branch' provided. Using 'trunk' as default value."
    BRANCH_NAME="trunk"
fi

git clone $CONFIG_base_remote -b $BRANCH_NAME $PROJECT_NAME

echo

create_config $PROJECT_NAME