#!/usr/bin/env bash

CONFIRM=0

while [[ $# -gt 0 ]]; do
    case $1 in
        -y)
            CONFIRM=1
            shift
            ;;
        -*|--*)
            print_error "Unknown option $1"
            exit 1
            ;;
        *)
            shift
            ;;
    esac
done

if [ ! -d "./$projectName" ]; then
    print_error "Project '$projectName' does not exist"
    exit 1
fi

create_config $projectName $CONFIRM