#!/usr/bin/env bash

PROJECT_NAME="platform"
BRANCH_NAME="trunk"

while [[ $# -gt 0 ]]; do
  case $1 in
    -n|--name)
      PROJECT_NAME="$2"
      shift
      shift
      ;;
    -b|--branch)
      BRANCH_NAME="$2"
      shift
      shift
      ;;
    -h|--help)
      print_help "Missing help for command 'create'!"
      exit 0
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      shift
      ;;
  esac
done

if [ -d "$PROJECT_NAME" ]; then
    print_error "Project with name '$PROJECT_NAME' already exists!"
    exit 1
fi

git clone $CONFIG_base_remote -b $BRANCH_NAME $PROJECT_NAME

start_instance "$PROJECT_NAME"