#!/usr/bin/env bash


PROJECT_NAME=""

while [[ $# -gt 0 ]]; do
  case $1 in
    -n|--name)
      PROJECT_NAME="$2"
      shift
      shift
      ;;
    -*|--*)
      print_error "Unknown option $1"
      exit 1
      ;;
    *)
      shift
      ;;
  esac
done

if [ -z "${PROJECT_NAME}" ]; then
    print_error "Missing required parameter --name"
    exit 1
fi

if [ ! -d "./$PROJECT_NAME" ]; then
    print_error "Project '$PROJECT_NAME' does not exist"
    exit 1
fi

use_project_dir $PROJECT_NAME

echo $(pwd)