#!/usr/bin/env bash

echo "Usage: $__PROGRAM_NAME <subcommand> [options]"
echo "Subcommands:"
for command in "$__COMMAND_DIR"/*
do
    echo "└ $(basename $command)"
done
echo ""
echo "Visit https://github.com/bschulzebaek/sw-devenv-cli#commands for details for each subcommand"
echo ""

print_info "Using $__PROGRAM_NAME:$__VERSION"

exit 0