#!/usr/bin/env bash

print_info "$__PROGRAM_NAME:$__VERSION"
echo
echo "$__PROGRAM_NAME <subcommand> [options]"

for command in "$__COMMAND_DIR"/*
do
    echo "└ $(basename $command)"
done

echo
print_help "Visit \e[4mhttps://github.com/bschulzebaek/sw-devenv-cli#commands\e[0m for reference!"

exit 0