#!/usr/bin/env bash

use_state_dir

source $projectName

data=`cat <<EOF
Service|Url
--------|----
Shopware|${shopwareUrl}
Adminer|http://127.0.0.1:${portAdminer}
Database|http://127.0.0.1:${portDatabase}
Installer|http://127.0.0.1:${portInstaller}
EOF`

echo
column -t -s "|" -n <<< $data
echo