#!/usr/bin/env bash

TOTAL_DIRS=$(find . -mindepth 1 -maxdepth 1 -type d -not -path '*/.*' | wc -l)

if [ $TOTAL_DIRS -eq 0 ]; then
    print_warn "No projects found in path '$CONFIG_base_directory'"
else
    print_info "Listing available instances (total: $TOTAL_DIRS)"
    find $(pwd) -mindepth 1 -maxdepth 1 -type d -not -path '*/.*'
fi
