#!/usr/bin/env bash

use_state_dir

source $projectName

if which sensible-browser >/dev/null; then
    sensible-browser $shopwareUrl
elif which xdg-open >/dev/null; then
    xdg-open $shopwareUrl
elif which gnome-open >/dev/null; then
    gnome-open $shopwareUrl
elif which open >/dev/null; then
    open $shopwareUrl
fi