#!/usr/bin/env bash

CONFIRM=0

while [[ $# -gt 0 ]]; do
    case $1 in
        -y)
            CONFIRM=1
            shift
            ;;
        -*|--*)
            print_error "Unknown option $1"
            exit 1
            ;;
        *)
            shift
            ;;
    esac
done

if [ $CONFIRM -ne 1 ]; then
    print_warn "This is a destructive operation and will break existing projects!"
    echo
    read -p "Confirm reset of assigned ports? y/n: " -n 1 -r
    echo

    if ! [[ $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

use_state_dir
rm ./assigned_ports 2> /dev/null || true

echo
print_warn "Done. Run 'swdev create-config <name>' to assign new ports to a project."