#!/usr/bin/env bash

PROJECT_NAME=""
HIDDEN=false

while [[ $# -gt 0 ]]; do
    case $1 in
        -n|--name)
            PROJECT_NAME="$2"
            shift
            shift
            ;;
        -q|--quiet)
            print_warn "Option --quiet currently is not implemented!"
            HIDDEN=true
            shift
            ;;
        -*|--*)
            print_error "Unknown option $1"
            exit 1
            ;;
        *)
            shift
            ;;
    esac
done

if [ -z "${PROJECT_NAME}" ]; then
    print_error "Missing required parameter --name"
    exit 1
fi

if [ ! -d "./$PROJECT_NAME" ]; then
    print_error "Project '$PROJECT_NAME' does not exist"
    exit 1
fi

use_project_dir $PROJECT_NAME
start_instance $HIDDEN