#!/usr/bin/env bash

HIDDEN=false

while [[ $# -gt 0 ]]; do
    case $1 in
        -q|--quiet)
            print_warn "Option --quiet currently is not implemented!"
            HIDDEN=true
            shift
            ;;
        -*|--*)
            print_error "Unknown option $1"
            exit 1
            ;;
        *)
            shift
            ;;
    esac
done

if [ ! -d "./$projectName" ]; then
    print_error "Project '$projectName' does not exist"
    exit 1
fi

use_project_dir
start_instance $HIDDEN