#!/usr/bin/env bash

HIDDEN=false

while [[ $# -gt 0 ]]; do
    case $1 in
        -q)
            print_warn "Option -q currently is not implemented!"
            HIDDEN=true
            shift
            ;;
        -*|--*)
            print_error "Unknown option $1"
            exit 1
            ;;
        *)
            shift
            ;;
    esac
done

use_project_dir

if [ ! -f "./devenv.local.nix" ]; then
    print_warn "Project '$projectName' does not have a 'devenv.local.nix' file. Run 'swdev create-config $projectName' first, to make sure all services work."
    echo
fi

start_instance $HIDDEN