#!/usr/bin/env bash

while [[ $# -gt 0 ]]; do
    case $1 in
        -*|--*)
            print_error "Unknown option $1"
            exit 1
            ;;
        *)
            shift
            ;;
    esac
done

use_project_dir
stop_instance