#!/usr/bin/env bash

while [[ $# -gt 0 ]]; do
    case $1 in
        -*|--*)
            print_error "Unknown option $1"
            exit 1
            ;;
        *)
            shift
            ;;
    esac
done

if [ ! -d "./$projectName" ]; then
    print_error "Project '$projectName' does not exist"
    exit 1
fi

use_project_dir
stop_instance