#!/bin/bash

create_config() {
    use_project_dir
    override="${2:-0}"

    local configPath=$(pwd)/devenv.local.nix

    if [ $override -ne 1 ] && [ -f $configPath ]; then
        read -p "Config file already exists. Override? y/n: " -n 1 -r
        echo
        echo

        if ! [[ $REPLY =~ ^[Yy]$ ]]; then
            exit 0
        fi
    fi

    if test -f "$__PROGRAM_PATH/devenv.template.local.nix"; then
        cp $__PROGRAM_PATH/devenv.template.local.nix $configPath
    else
        cp $__PROGRAM_PATH/devenv.template.nix $configPath
    fi

    local appProtocol="http"
    local appUrl="$1.dev.localhost"
    local appPort=80

    sed -i -e "s/\__APP_PROTOCOL__/$appProtocol/;" $configPath
    sed -i -e "s/\__APP_URL__/$appUrl/;" $configPath
    sed -i -e "s/\__APP_PORT__/$appPort/;" $configPath

    local portPlaceholder="__REDIS_PORT__ __DATABASE_PORT__ __ADMINER_PORT__ __INSTALLER_PORT__ "

    for str in $portPlaceholder; do
        local tmpPort=$(get_unused_port)

        sed -i -e "s/\\$str/$tmpPort/;" $configPath
    done

    use_project_dir

    print_info "Config location: $configPath"
    echo
    print_info "Your instance will be available at $appProtocol://$appUrl"
    print_info "Run 'swdev start $1' to apply the config."
    echo
    print_info "If this instance is new or updated, run 'composer setup' inside the shell next."
}