#!/bin/bash

get_unused_port() {
    while :
    do
        PORT="`shuf -i $CONFIG_devenv_ports_start-$CONFIG_devenv_ports_end -n 1`"
        ss -lpn | grep -q ":$PORT " || break
    done

    echo $PORT
}