#!/bin/bash

get_os() {
    unameOut="$(uname -s)"

    case "${unameOut}" in
        Linux*)     machine=Linux;;
        Darwin*)    machine=Mac;;
        *)          machine="UNKNOWN:${unameOut}"
    esac

    echo ${machine}
}