#!/usr/bin/env bash

COLOR_OFF='\033[0m'
COLOR_RED='\033[0;31m'
COLOR_BLUE='\033[0;34m'
COLOR_YELLOW='\033[0;33m'
COLOR_GREEN='\033[0;32m'

print_error() {
    echo -e "$COLOR_RED[ERROR]$COLOR_OFF $1"
}

print_info() {
    echo -e "$COLOR_BLUE[INFO]$COLOR_OFF $1"
}

print_warn() {
    echo -e "$COLOR_YELLOW[WARN]$COLOR_OFF $1"
}

print_help() {
    echo -e "$COLOR_GREEN[HELP]$COLOR_OFF $1"
}