#!/usr/bin/env bash

use_working_dir() {
    mkdir -p $CONFIG_base_directory

    cd $CONFIG_base_directory
}

use_state_dir() {
    local dir="${CONFIG_base_directory}/.state"

    mkdir -p $dir

    cd $dir
}

use_project_dir() {
    use_working_dir

    cd $projectName
}

use_plugin_dir() {
  use_working_dir

  mkdir -p custom/plugins

  cd custom/plugins
}

use_program_dir() {
    cd $__PROGRAM_PATH
}
