#!/usr/bin/env bash

use_working_dir() {
    local dir="${CONFIG_base_directory}"

    mkdir -p $dir
    cd $dir
}

use_project_dir() {
    use_working_dir

    cd $1
}

use_program_dir() {
    cd $__PROGRAM_PATH
}